import React from "react";
import Head from 'next/head';

import { Header } from "../components/Header/Header";
import Sidebar from "../components/Sidebar/SideBar";
import { MainContainer } from "../styles/main.style";
import { AboutMe } from "../components/AboutMe/AboutMe";

function MainPage(){
    return (
        <>
            <Head>
                <title>김지한 포트폴리오</title>
                <meta name="description" content="Generated by create next app" />
                <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico" /> 
            </Head>
            <Sidebar/>
            <Header/>
            <MainContainer>
                <AboutMe/>
            </MainContainer>
        </>
    )
}

export default MainPage;